name: Node.js Package

on:
    release:
        types: [created]

jobs:
    publish-npm:
        # needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 10
                  registry-url: https://registry.npmjs.org/
            - run: npm install -g yarn # Extra Step
            - run: yarn install --quiet
            - run: echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
            - run: yarn publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
